[package]
name = "struct-bench"
version = "0.1.0"
authors = ["KirFed <f3kilo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
